name: "godot-tester"
description: "Runs all GUT tests you have for your Godot game"
inputs:
  version:
    description: "Your Godot version number e.g. 3.2.2"
    required: true
    default: "3.2.2"
  path:
    description: "Give relative path to your project.godot, if not in top level of repo"
    required: false
    default: "./"
  release-type:
    description: "Release type e.g. stable (the default)"
    required: false
    default: "stable"

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - ${{ inputs.version }}
  - ${{ inputs.path }}
  - ${{ inputs.is-mono }}

branding:
  icon: 'chevron-right'  
  color: 'green'
