name: Build tester

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        version: "4.0.3"
        path: "tester_GUT_v9.0.1"
        minimum-pass: "0.6"
        test-dir: "res://test"
        config-file: "res://.gutconf.json"
    - uses: ./
      with:
        version: "4.0.3"
        path: "tester_GUT_v9.0.1"
        release_type: "rc2"
    - uses: ./
      with:
        version: "4.0.3"
        path: "tester_GUT_v9.0.1"
        minimum-pass: "0.6"
        direct-scene: "test/alt_mode/tests.tscn"
        result-output-file: "direct_scene_xml_output.xml"
        config-file: "res://.gutconf.json"
    - uses: ./
      with:
        version: "4.0.3"
        path: "tester_GUT_v9.0.1"
        test-timeout: "45"
        minimum-pass: "0.6"
        direct-scene: "test/alt_mode/tests.tscn"
        result-output-file: "direct_scene_xml_output.xml"
        assert-check: "true"
        max-fails: "6"
    - uses: ./
      with:
        version: "4.0.3"
        path: "tester_GUT_v9.0.1"
        release_type: "rc2"
        is-mono: "true"
        test-timeout: "45"
        minimum-pass: "0.7"
        assert-check: "false"
        max-fails: "2"
    - uses: ./
      with:
        version: "3.2.1"
        is-mono: "true"
        path: "tester_GUT_v7.4.1"
        import-time: "5"
        test-timeout: "45"
        minimum-pass: "0.6"
        test-dir: "res://test"
        config-file: "res://.gutconf.json"
    - uses: ./
      continue-on-error: true
      with:
        version: "3.2.2"
        path: "tester_GUT_v7.4.1"
        test-timeout: "2"
        minimum-pass: "0.7"
        ignore-errors: "true"
    - uses: ./
      continue-on-error: true
      with:
        version: "3.2.2"
        path: "tester_GUT_v7.4.1"
        test-timeout: "2"
        minimum-pass: "0.8"
    - uses: ./
      continue-on-error: true
      with:
        version: "3.2.2"
        path: "tester_GUT_v7.4.1"
    - uses: ./
      continue-on-error: true
      with:
        version: "3.4"
        release_type: "rc2"
        path: "tester_GUT_v7.4.1"
    - uses: ./
      with:
        version: "3.2.2"
        path: "tester_GUT_v7.4.1"
        test-timeout: "45"
        minimum-pass: "0.7"
        direct-scene: "test/alt_mode/tests.tscn"
        result-output-file: "direct_scene_xml_output.xml"
        config-file: "res://.gutconf.json"
        ignore-errors: "true"
    - uses: ./
      with:
        version: "3.2.2"
        path: "tester_GUT_v7.4.1"
        test-timeout: "45"
        minimum-pass: "0.7"
        direct-scene: "test/alt_mode/tests.tscn"
        result-output-file: "direct_scene_xml_output.xml"
        assert-check: "true"
    - uses: ./
      continue-on-error: true
      with:
        version: "3.2.2"
        path: "tester_GUT_v7.4.1"
        test-timeout: "45"
        minimum-pass: "0.7"
        assert-check: "false"
        max-fails: "2"
    - uses: ./
      with:
        version: "3.2.2"
        path: "tester_GUT_v7.4.1"
        test-timeout: "45"
        minimum-pass: "0.7"
        direct-scene: "test/alt_mode/tests.tscn"
        result-output-file: "direct_scene_xml_output.xml"
        assert-check: "true"
        max-fails: "6"