name: Build tester

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        version: "3.2.1"
        is-mono: "true"
        path: "tester"
        import-time: "5"
        test-timeout: "45"
        minimum-pass: "0.6"
        test-dir: "res://test"
        config-file: "res://.gutconf.json"
    - uses: ./
      continue-on-error: true
      with:
        version: "3.2.2"
        path: "tester"
        test-timeout: "2"
        minimum-pass: "0.7"
        ignore-errors: "true"
    - uses: ./
      continue-on-error: true
      with:
        version: "3.2.2"
        path: "tester"
        test-timeout: "2"
        minimum-pass: "0.8"
    - uses: ./
      continue-on-error: true
      with:
        version: "3.2.2"
        path: "tester"
    - uses: ./
      continue-on-error: true
      with:
        version: "3.4"
        release_type: "rc2"
        path: "tester"
    - uses: ./
      with:
        version: "3.2.2"
        path: "tester"
        test-timeout: "45"
        minimum-pass: "0.7"
        direct-scene: "test/alt_mode/tests.tscn"
        config-file: "res://.gutconf.json"
        ignore-errors: "true"
    - uses: ./
      with:
        version: "3.2.2"
        path: "tester"
        test-timeout: "45"
        minimum-pass: "0.7"
        direct-scene: "test/alt_mode/tests.tscn"
        assert-check: "true"
    - uses: ./
      continue-on-error: true
      with:
        version: "3.2.2"
        path: "tester"
        test-timeout: "45"
        minimum-pass: "0.7"
        assert-check: "false"
        max-fails: "2"
    - uses: ./
      with:
        version: "3.2.2"
        path: "tester"
        test-timeout: "45"
        minimum-pass: "0.7"
        direct-scene: "test/alt_mode/tests.tscn"
        assert-check: "true"
        max-fails: "6"