name: Build tester

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        version: "3.2.1"
        release-type: "stable"
        path: "tester"